// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POES.Data;

#nullable disable

namespace POES.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POES.Entities.Arrival", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ArrivedQuantity")
                        .HasColumnType("float");

                    b.HasKey("OrderNumber", "Position");

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("POES.Entities.FirstFreeNumber", b =>
                {
                    b.Property<string>("NumberGroup")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FirstFreeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("NumberGroup");

                    b.ToTable("FirstFreeNumbers");
                });

            modelBuilder.Entity("POES.Entities.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(37)
                        .HasColumnType("nvarchar(37)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GrossWeight")
                        .HasColumnType("float");

                    b.Property<double>("InventoryAllocated")
                        .HasColumnType("float");

                    b.Property<double>("InventoryOnHand")
                        .HasColumnType("float");

                    b.Property<double>("InventoryOnOrder")
                        .HasColumnType("float");

                    b.Property<string>("ItemText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NetWeight")
                        .HasColumnType("float");

                    b.Property<int>("Packing")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Variety")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemCode");

                    b.HasIndex("SupplierCode", "ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("POES.Entities.POHeader", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("OrderNumber");

                    b.HasIndex("SupplierCode");

                    b.ToTable("POHeaders");
                });

            modelBuilder.Entity("POES.Entities.POLine", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(37)");

                    b.Property<double>("OrderedQuantity")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("OrderNumber", "Position");

                    b.HasIndex("ItemCode");

                    b.HasIndex("OrderNumber", "ItemCode")
                        .IsUnique();

                    b.ToTable("POLines");
                });

            modelBuilder.Entity("POES.Entities.Parameter", b =>
                {
                    b.Property<long>("SeqNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeqNo"));

                    b.Property<string>("CreatedByLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberGroupPurchaseOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberGroupSupplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeqNo");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("POES.Entities.Supplier", b =>
                {
                    b.Property<string>("SupplierCode")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierCode");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("POES.Entities.Arrival", b =>
                {
                    b.HasOne("POES.Entities.POLine", "Line")
                        .WithMany("Arrivals")
                        .HasForeignKey("OrderNumber", "Position")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("POES.Entities.Item", b =>
                {
                    b.HasOne("POES.Entities.Supplier", "Supplier")
                        .WithMany("Items")
                        .HasForeignKey("SupplierCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("POES.Entities.POHeader", b =>
                {
                    b.HasOne("POES.Entities.Supplier", "Supplier")
                        .WithMany("POHeaders")
                        .HasForeignKey("SupplierCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("POES.Entities.POLine", b =>
                {
                    b.HasOne("POES.Entities.Item", "Item")
                        .WithMany("POLines")
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("POES.Entities.POHeader", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Header");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("POES.Entities.Item", b =>
                {
                    b.Navigation("POLines");
                });

            modelBuilder.Entity("POES.Entities.POHeader", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("POES.Entities.POLine", b =>
                {
                    b.Navigation("Arrivals");
                });

            modelBuilder.Entity("POES.Entities.Supplier", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("POHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
